### ISSUE TITLE
WebAppRunner.

### ISSUE THREAD

**Issue by IrinaBurnina** [IrinaBurnina/Servlet#2]
# Вопрос по второму заданию.
## Не совсем понимаю, что считать результатом выполнения этого задания. Полагаю, что должен выполняться код из первого задания после запуска программы. ?

После дополнения плагинов на очистку, компиляцию и веб архивацию, выдал ошибку об отсутствии папки conf: "Error running 'tomCatRunner': Conf folder in Tomcat installation is missing!" - причем путь в настройках конфигурации подтянулся сам (я его не настраивала: E:/ApacheTomcat/apache-tomcat-9.0.79/webapp), поэтому пришлось подкорректировать до E:/ApacheTomcat/apache-tomcat-9.0.79 и ошибка ушла.

Провела заново сборку, запустила и получила такую информацию в логе:

сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version name:   Apache Tomcat/9.0.79
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Aug 8 2023 20:41:26 UTC
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version number: 9.0.79.0
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Windows 10
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Версия ОС:             10.0
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Архитектура:           amd64
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             C:\Users\Ира\.jdks\openjdk-18.0.1.1
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Версия JVM:            18.0.1.1+2-6
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Oracle Corporation
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         E:\ApacheTomcat\apache-tomcat-9.0.79
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         E:\ApacheTomcat\apache-tomcat-9.0.79
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dvisualvm.id=1320862338135300
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -javaagent:C:\Users\Ира\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\222.3739.54\lib\idea_rt.jar=62104:C:\Users\Ира\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\222.3739.54\bin
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=windows-1251
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dsun.stdout.encoding=windows-1251
сент. 05, 2023 9:38:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dsun.stderr.encoding=windows-1251
сент. 05, 2023 9:38:50 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [C:\Users\Ира\.jdks\openjdk-18.0.1.1\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\Git\cmd;C:\Users\Ира\AppData\Local\Microsoft\WindowsApps;;C:\Users\Ира\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Ира\AppData\Local\JetBrains\Toolbox\scripts;.]
сент. 05, 2023 9:38:52 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
сент. 05, 2023 9:38:53 PM org.apache.catalina.startup.Catalina load
INFO: Server initialization in [4606] milliseconds
сент. 05, 2023 9:38:53 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Catalina]
сент. 05, 2023 9:38:53 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/9.0.79]
сент. 05, 2023 9:38:53 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\Servlets-1.0-SNAPSHOT.war]
сент. 05, 2023 9:38:58 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
сент. 05, 2023 9:38:58 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\Servlets-1.0-SNAPSHOT.war] has finished in [5 491] ms
сент. 05, 2023 9:38:58 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Установка веб приложения в папку [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\docs]
сент. 05, 2023 9:38:59 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\docs] has finished in [67] ms
сент. 05, 2023 9:38:59 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Установка веб приложения в папку [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\examples]
сент. 05, 2023 9:38:59 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextInitialized()
сент. 05, 2023 9:38:59 PM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextInitialized()
сент. 05, 2023 9:38:59 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: attributeAdded('StockTicker', 'async.Stockticker@2fd4312a')
сент. 05, 2023 9:38:59 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\examples] has finished in [711] ms
сент. 05, 2023 9:38:59 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Установка веб приложения в папку [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\host-manager]
сент. 05, 2023 9:38:59 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\host-manager] has finished in [65] ms
сент. 05, 2023 9:38:59 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Установка веб приложения в папку [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\manager]
сент. 05, 2023 9:38:59 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\manager] has finished in [45] ms
сент. 05, 2023 9:38:59 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Установка веб приложения в папку [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\ROOT]
сент. 05, 2023 9:38:59 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\ROOT] has finished in [28] ms
сент. 05, 2023 9:38:59 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
сент. 05, 2023 9:39:00 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in [6961] milliseconds
# Ошибок я не увидела в лог-файле, но код не выполняется из первого задания. Что осталось неисправленным? - не пойму.

# Ссылка на [исходный код](https://github.com/netology-code/jspr-code/tree/master/04_serlvets/servlets)
# Java & Windows
ОС: Windows 10 Pro
Версия:21.Н.2
Разрядность: 64
Версия java: 11.0.16

**Comment by IrinaBurnina** [comment]
# После смены на 11 версию JDK
Пустого списка при запросе в браузере http://localhost:8080/api/posts не получила.
Лог файл:
C:\Users\Ира\.jdks\corretto-11.0.16.1\bin\java.exe -Dvisualvm.id=1824535294634100 -javaagent:C:\Users\Ира\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\222.3739.54\lib\idea_rt.jar=57976:C:\Users\Ира\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\222.3739.54\bin -Dfile.encoding=windows-1251 -classpath E:\ApacheTomcat\apache-tomcat-9.0.79\bin\bootstrap.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\bin\commons-daemon.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\bin\tomcat-juli.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\annotations-api.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\catalina-ant.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\catalina-ha.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\catalina-ssi.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\catalina-storeconfig.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\catalina-tribes.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\catalina.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\ecj-4.20.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\el-api.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\jasper-el.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\jasper.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\jaspic-api.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\jsp-api.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\servlet-api.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-api.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-coyote.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-dbcp.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-i18n-cs.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-i18n-de.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-i18n-es.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-i18n-fr.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-i18n-ja.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-i18n-ko.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-i18n-pt-BR.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-i18n-ru.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-i18n-zh-CN.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-jdbc.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-jni.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-util-scan.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-util.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\tomcat-websocket.jar;E:\ApacheTomcat\apache-tomcat-9.0.79\lib\websocket-api.jar org.apache.catalina.startup.Bootstrap start
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version name:   Apache Tomcat/9.0.79
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Aug 8 2023 20:41:26 UTC
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version number: 9.0.79.0
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Windows 10
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Версия ОС:             10.0
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Архитектура:           amd64
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             C:\Users\Ира\.jdks\corretto-11.0.16.1
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Версия JVM:            11.0.16.1+9-LTS
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Amazon.com Inc.
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         E:\ApacheTomcat\apache-tomcat-9.0.79
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         E:\ApacheTomcat\apache-tomcat-9.0.79
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dvisualvm.id=1824535294634100
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -javaagent:C:\Users\Ира\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\222.3739.54\lib\idea_rt.jar=57976:C:\Users\Ира\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\222.3739.54\bin
сент. 11, 2023 5:30:28 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=windows-1251
сент. 11, 2023 5:30:28 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [C:\Users\Ира\.jdks\corretto-11.0.16.1\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\Git\cmd;C:\Users\Ира\AppData\Local\Microsoft\WindowsApps;;C:\Users\Ира\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Ира\AppData\Local\JetBrains\Toolbox\scripts;.]
сент. 11, 2023 5:30:29 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
сент. 11, 2023 5:30:29 PM org.apache.catalina.startup.Catalina load
INFO: Server initialization in [1241] milliseconds
сент. 11, 2023 5:30:29 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Catalina]
сент. 11, 2023 5:30:29 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/9.0.79]
сент. 11, 2023 5:30:29 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\Servlets-1.0-SNAPSHOT.war]
сент. 11, 2023 5:30:32 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
сент. 11, 2023 5:30:32 PM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
WARNING: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [341] milliseconds.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
сент. 11, 2023 5:30:33 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\Servlets-1.0-SNAPSHOT.war] has finished in [4 312] ms
сент. 11, 2023 5:30:33 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Установка веб приложения в папку [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\docs]
сент. 11, 2023 5:30:34 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\docs] has finished in [43] ms
сент. 11, 2023 5:30:34 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Установка веб приложения в папку [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\examples]
сент. 11, 2023 5:30:34 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextInitialized()
сент. 11, 2023 5:30:34 PM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextInitialized()
сент. 11, 2023 5:30:34 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: attributeAdded('StockTicker', 'async.Stockticker@308d4981')
сент. 11, 2023 5:30:34 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\examples] has finished in [413] ms
сент. 11, 2023 5:30:34 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Установка веб приложения в папку [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\host-manager]
сент. 11, 2023 5:30:34 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\host-manager] has finished in [38] ms
сент. 11, 2023 5:30:34 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Установка веб приложения в папку [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\manager]
сент. 11, 2023 5:30:34 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\manager] has finished in [37] ms
сент. 11, 2023 5:30:34 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Установка веб приложения в папку [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\ROOT]
сент. 11, 2023 5:30:34 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [E:\ApacheTomcat\apache-tomcat-9.0.79\webapps\ROOT] has finished in [30] ms
сент. 11, 2023 5:30:34 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
сент. 11, 2023 5:30:34 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in [5341] milliseconds
сент. 11, 2023 5:30:42 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030xbds$0xb40xccr0xc3j00xb4!0x82YR)0xb6I0x9a0xa00xd5H~0xe80x150x070x130x810x9710x1bY# ]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

сент. 11, 2023 5:30:42 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030x950xf30xf70xe00xf70x9eq0x840xfcn0xa10x8c0xa00xd00x14g2DP!s0x110x86h0x170xab0x9b{c0xaf0x11s ]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

сент. 11, 2023 5:30:42 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03M0xee0xb40x9f0x8d0xcd0xbd10x980xc70xd70x9c0xa70x010x1f0xfb=0xa70xb20xb6]0x960x1cZ$0x013*0xda0x9cjE ]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by IrinaBurnina** [comment]
# Настройки конфигурации запуска
![image](https://github.com/IrinaBurnina/Servlet/assets/115548107/8fda0c68-61d6-466e-8969-2dd64d86979a)

# Настройка  конфигурации Tom Cat для первой части задания 
![image](https://github.com/IrinaBurnina/Servlet/assets/115548107/9efc4bd6-5fe7-4393-8417-f8dc733694e4)
